jwtExistingSecret: shophub-jwt-static

grafana:
  url: http://kube-prometheus-stack-grafana.monitoring
  externalUrl: http://grafana.localhost:8080
  adminUser: admin
  existingSecret: grafana-admin

discord:
  guildId: "1508273714897092648"
  botTokenSecret:
    name: discord-bot-token
    namespace: shophub
