loki:
  enabled: true
  isDefault: false
  image:
    tag: 2.9.10
  persistence:
    enabled: false    # nema persistance da ne gomilamo gomile starih logova, stedimo resurse

promtail:
  enabled: true

grafana:
  enabled: false
prometheus:
  enabled: false    # ne pravi svoju grafanu i prometheus, koristi iz kube prometehus stacka
                    # da se to ne iskljuci imali bi duplu grafanu
