# Mnogo db CR-ovi zive u tenant namespacovima korisnika, jedan po shophub korisniku,
# Ali je zato operator instaliran u svom namespaceu, po defaultu on gleda samo svoj namespace,
# nebi video ni jedan CR, njih niko ne reconciluje, shop bude zaglavljen,
# Zato prosirmo da on gleda sve namespacove,
operator:
  watchNamespace: "*"
