apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shophub
  namespace: argocd
spec:
  description: ShopHub platform — GitOps-managed cluster state.
  # samo sa ovih repoa sme da povlaci
  sourceRepos:
    - https://github.com/shophub-devoops/kube-state.git
    - https://cloudnative-pg.github.io/charts
    - https://mongodb.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - registry-1.docker.io/urospetraskovic    # moj OCI
  destinations:           # u koje destinacije tj u koje namespaceove sme da instalira
    - namespace: '*'      # u bilo koji namespace
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:   # sme da pravi klaster globalne resurse, CRD i cluster role
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
