# AgroCD po konvenciji drzi repo konfiguraciju u secretima jer cesto zadrze kredencijale
apiVersion: v1  # ali nasi chartovi su javni i nemaju kredencijale
kind: Secret
metadata:
  name: urospetraskovic-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository  # postoji OCI Helm registry na dockerhub sa tvojim chartovima
stringData:
  name: urospetraskovic-oci
  type: helm
  url: registry-1.docker.io/urospetraskovic
  enableOCI: "true"   # moji chartovi shophub i shop operator su objavljeni kao OCI artefakti na dockerhubu
                      
