apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shophub
  source:
    repoURL: https://github.com/shophub-devoops/kube-state.git
    targetRevision: main
    path: argocd/apps       # gleda ceo folder, svaki yaml u njemu tretiraj kao application
    directory:
      recurse: true         # i podfoldere
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true           # ako obrisemo app iz gita on se obrise i u klasteru
      selfHeal: true        # ako neko izmeni resurs u klasteru agroCD ga vrati na ono sto ide u gitu
    syncOptions:
      - CreateNamespace=true
